myapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path



urlpatterns =[
    path('',views.home,name='home'),
    path('register/',views.register_view,name='register'),
    path('dashboard/',views.dashboard_view,name='dashboard'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('task/',views.task,name='task'),
    path('task/add/',views.add_task,name='task-add'),
    path('task/edit/<int:id>/',views.task_edit,name='task-edit'),
    path('task/delete/<int:id>/',views.task_delete,name='task-delete'),
    path('profile/update/',views.profile_edit,name='profile-update'),
     path('change-password/', views.change_password, name='change_password'),
    path('chart-data/', views.get_chart_data, name='get_chart_data'),
    path("fetch-tasks-weekly/", views.fetch_tasks_weekly, name="fetch_tasks_weekly"),
    path("fetch-tasks-monthly/", views.fetch_tasks_monthly, name="fetch_tasks_monthly"),
    path("calendar/", views.calendar, name="calendar"),
    path('login2/',views.login2,name='login2') 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theweeklymuse/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import time
from django.utils.timezone import now

# Create your models here.

#Task Model
class Task(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField()
    status = models.CharField(max_length=25,default='Incomplete')
    date = models.DateField(auto_now_add=True)
    finishDate = models.DateField(null=True, blank=True)
    start_time=models.TimeField()
    end_time=models.TimeField()
    priority=models.CharField(max_length=25,default='Unmark')
    username=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    fname = models.CharField(max_length=100)
    email = models.EmailField(default='example@gmail.com', blank=True, null=True)
    profile_pic =models.ImageField(upload_to='profile_pics/',default='static/images/default.svg')

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        email = instance.email.strip() if instance.email else 'example@gmail.com'

        full_name = f"{instance.first_name} {instance.last_name}".strip()
        Profile.objects.create(
            user=instance,
            email=email,
            fname=full_name if full_name else instance.username
        )


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if hasattr(instance, 'profile'):
        instance.profile.save()

templates/partials/alertMessage.html
<!-- Alert Message Codes -->

<!-- Create Task -->
<div id="taskAlertAdd" class="alert alert-success alert-dismissible fade show popdiv" role="alert" style="display: none;">
    Task created Successfully!
</div>

<!-- Update Task  -->
<div id="taskAlertEdit" class="alert alert-success alert-dismissible fade show popdiv" role="alert" style="display: none;">
    Task Updated Successfully!
</div>

<!-- Delete Task -->
<div id="taskAlertDelete" class="alert alert-success alert-dismissible popdiv" role="alert" style="display: none;">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <strong>Task Deleted Successfully!</strong> 
</div>

<!-- Profile Update -->
<div id="profileAlertEdit" class="alert alert-success alert-dismissible fade show popdiv" role="alert" style="display: none;">
    Profile Updated Successfully!
</div>

<!-- Update Password -->
<div id="updatePasswordAlert" class="alert alert-success alert-dismissible fade show popdivlogout" role="alert" style="display: none;">
    Password Updated Successfully. Please Login Again With New Password.
    <strong>Redirecting You To Login Page.</strong>
</div>

<!-- Old Password Error-->
<div id="oldPasswordAlert" class="alert alert-success alert-dismissible fade show popdiv" role="alert" style="display: none;">
    Old Password Is Incorrect.
</div>

<!-- New Password Error-->
<div id="newPasswordAlert" class="alert alert-success alert-dismissible fade show popdiv" role="alert" style="display: none;">
    New  Password Is Not Matched.
</div>

<!-- Password Validation  Error-->
<div id="passwordValidationAlert" class="alert alert-success alert-dismissible fade show popdiv" role="alert" style="display: none;">
    Password Must Be 8 character long. Choose a Strong Password.
    
</div>

templates/partials/calendar.html
{% load custom_tags %}

<!-- Month summary -->
<div class="row">
  <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
    <div class="calendarDetail">
      <button id="prevMonth" data-bs-toggle="tooltip" data-bs-placement="left" title="Last Month">
        <i class="bi bi-caret-left-fill"></i>
      </button>
      <div id="currentMonth">
        <span>{{ data.month|date:"F" }} , {{ current_year }}</span>
      </div>
      <button id="nextMonth" data-bs-toggle="tooltip" data-bs-placement="right" title="Next Month">
        <i class="bi bi-caret-right-fill"></i>
      </button>
    </div>
  </div>

  <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
    <div class="calendarDetail">
      <i class="bi bi-calendar-week-fill" data-bs-toggle="tooltip"></i>
      Created Task: {{ data.taskCreated }}
    </div>
  </div>

  <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
    <div class="calendarDetail">
      <i class="bi bi-hourglass-split" data-bs-toggle="tooltip"></i>
      Pending Task: {{ data.Incomplete }}
    </div>
  </div>
</div>

<!-- Calendar Grid -->
<div class="calendarContainer">
  <div class="row">
    {% for day in days_in_month %}
      {% with day_str=day|stringformat:"02d" %}
        {% with date_str=current_year|stringformat:"s"|add:"-"|add:current_month|stringformat:"s"|add:"-"|add:day_str %}
          {% with day_tasks=tasks_by_day|get_item:date_str %}
            <div class="col-xl-2 col-lg-2 col-md-3 col-sm-4 col-6">
              <div class="taskMonthly {% if date_str == formatted_today %}today{% endif %}">
                <div class="dayNumber">{{ day }}</div>

                {% if day_tasks %}
                  {% for task in day_tasks %}
                    <div class="taskDetails">
                      <div class="icon">
                        <!-- Edit -->
                        <a href="#" class="edit-task" data-task-id="{{ task.id }}" data-bs-toggle="modal"
                        data-bs-target="#editTaskModal">
                        <i class="bi bi-eye-fill" title="Edit"></i>
                        </a>
                      </div>
                      <div class="taskName">{{ task.name }}</div>
                    </div>
                  {% endfor %}
                {% else %}
                  <div class="noTask">
                    <span>No Task</span>
                  </div>
                {% endif %}
              </div>
            </div>
          {% endwith %}
        {% endwith %}
      {% endwith %}
    {% endfor %}
  </div>
</div>

templates/partials/cardbody.html
<div class="row">
    <div class="col-12">
        <h4>Showing Task From {{cardData.start_of_month}} To {{cardData.end_of_month}}</h3>
    </div>
</div>
<div class="row">
    {% for task in page_task %}
    <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4 col-6 mb-3">
        <div class="taskbody">
            <div class="tasktitle">{{task.name}}</div>
            <div class="taskdesc">{{task.description}}</div>
            <div class="taskFooter">
                {% if task.status == 'Incomplete'%}
                <i class="bi bi-hourglass-split text-secondary" data-bs-toggle="tooltip" title="Pending"></i>
                {% else %}
                <i class="bi bi-check-square-fill text-success" data-bs-toggle="tooltip" title="Completed"></i>
                {% endif %}
                {% if task.priority == 'Unmark' %}
                <i class='bi bi-bookmark-dash-fill text-info' data-bs-toggle="tooltip" title="Unmark"></i>
                {% elif task.priority == 'Flagged' %}
                <i class='bi bi-flag-fill text-warning' data-bs-toggle="tooltip" title="Flagged"></i>
                {% else %}
                <i class='bi bi-star-fill text-warning' data-bs-toggle="tooltip" title="Star"></i>
                {% endif %}
                <!-- Edit Button -->
                <a href="#" class="edit-task" data-task-id="{{ task.id }}" data-bs-toggle="modal"
                    data-bs-target="#editTaskModal">
                    <i class="bi bi-pencil-square text-secondary" data-bs-toggle="tooltip" title="Edit"></i>
                </a>

                <!-- Delete Button -->
                <a href="#" class="delete-task" data-task-id="{{ task.id }}" data-bs-toggle="modal"
                    data-bs-target="#deleteTaskModal">
                    <i class="bi bi-trash3-fill text-danger" data-bs-toggle="tooltip" title="Delete"></i>
                </a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="centerElementDiv" id="noTaskDiv">
        <h2>You Don't Have Any Task In This Month</h2>
    </div>        
    {% endfor %}
</div>

templates/partials/changePassword.html
<!-- EDIT PROFILE POPUP MODEL -->
<div class="modal fade" id="updatePasswordModal" tabindex="-1" aria-labelledby="updatePasswordLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updatePasswordLabel">Update Password</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
               
               <form id="updatePasswordForm">
                {% csrf_token %}
                
                <div class="mb-3">
                    <label for="old_password">Old Password</label>
                    <input type="password" id="old_password" name="old_password" class="form-control">
                </div>
            
                <div class="mb-3">
                    <label for="new_password1">New Password</label>
                    <input type="password" id="new_password1" name="new_password1" class="form-control">
                </div>
            
                <div class="mb-3">
                    <label for="new_password2">Confirm New Password</label>
                    <input type="password" id="new_password2" name="new_password2" class="form-control">
                </div>
            
                <button type="submit" class="btn btn-primary">Change Password</button>
            </form>
            </div>
        </div>
    </div>
</div>

templates/partials/editprofile.html
<!-- EDIT PROFILE POPUP MODEL -->
<div class="modal fade" id="EditProfileModal" tabindex="-1" aria-labelledby="EditProfileLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="EditProfileLabel">Edit Profile</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="editProfileForm" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <!-- Show validation errors here -->
                    <div id="error-div" style="color: red; display: none;"></div>


                    <div class="mb-3 imageProfile">
                        <img id="profile-preview" src="{{request.user.profile.profile_pic.url }}" alt="Profile_picture">
                        <input type="file" id="id_profile_pic" name="profile_pic" accept="image/*"
                            onchange="previewImage(event)" class="form-control">
                    </div>

                    <div class="mb-3">
                        <label for="fname" class="form-label">Full Name</label>
                        <input type="text" class="form-control" id="fname" name="fname"
                            value="{{request.user.profile.fname}}">
                    </div>

                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email"
                            value="{{request.user.profile.email}}">
                    </div>

                    <button type="submit" class="btn btn-primary">Update Profile</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal for full-screen image -->
<div class="modal fade" id="profileImageModal" tabindex="-1" aria-labelledby="profileImageLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                <div class="profilepic">
                    {% if request.user.profile.profile_pic.url %}
                    <img id="profilePicShow" src="{{ request.user.profile.profile_pic.url }}" alt="Profile Picture">
                    {% else %}
                    <img id="profilePicShow" src="/media/profile/default.svg" alt="Profile Picture">
                    {% endif%}
                </div>

            </div>
        </div>
    </div>
</div>

templates/partials/pagination.html
<!-- Pagination -->
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_task.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_task.previous_page_number }}">Previous</a></li>
        {% endif %}

        <li class="page-item active"><a class="page-link">{{ page_task.number }}</a></li>

        {% if page_task.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_task.next_page_number }}">Next</a>
        </li>
        <li class="page-item"><a class="page-link" href="?page={{ page_task.paginator.num_pages }}">Last</a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/partials/sidebar.html
{% load static %}
<!-- SIDEBAR HTML CODE -->
<nav class="sidebar" id="sidebar">
    <div class="sidebar__container">
       
        <div class="sidebar__user" id="sidebar_user">                 
            <div class="sidebar__img" data-bs-toggle="modal" data-bs-target="#profileImageModal">
                <img src="{{request.user.profile.profile_pic.url }}" alt="Profile_picture">
            </div>

            <div class="sidebar__info">
                <h3 style="text-transform: uppercase;">{{ request.user.username}}</h3>
                {%if request.user.profile.email %}
                <span>
                    <i class="bi bi-envelope"></i>
                    <span>{{request.user.profile.email}}</span>
                </span>
                {% endif%}
            </div>
        </div>

        <div class="sidebar__content">
            <div>
                <h3 class="sidebar__title">MANAGE</h3>
                     
                <div class="sidebar__list">
                    <a href="{% url 'dashboard' %}" class="sidebar__link active-link">
                        <i class='bx bxs-dashboard' data-bs-toggle="tooltip" data-bs-placement="right" title="Dashboard" ></i>
                        <span>Dashboard</span>
                    </a>

                    <a href="{% url 'task' %}" class="sidebar__link">
                        <i class='bx bx-task' data-bs-toggle="tooltip" data-bs-placement="right" title="Task"></i>
                        <span>Task</span>
                    </a>   
                    
                    <a href="{% url 'calendar' %}" class="sidebar__link">
                        <i class='bi bi-calendar3' data-bs-toggle="tooltip" data-bs-placement="right" title="Calendar"></i>
                        <span>Calendar</span>
                    </a> 

                </div>
            </div>

            <div>
                <h3 class="sidebar__title">SEETINGS</h3>

                <div class="sidebar__list">
                    <a href="#" data-bs-toggle="modal" data-bs-target="#EditProfileModal" class="sidebar__link">
                        <i class='bi bi-pencil-fill' data-bs-toggle="tooltip" data-bs-placement="right" title="Edit Profil"></i>
                        <span>Edit Profile</span>
                    </a>

                    <a href="#" class="sidebar__link" data-bs-toggle="modal" data-bs-target="#updatePasswordModal">
                        <i class='bi bi-file-earmark-lock-fill' data-bs-toggle="tooltip" data-bs-placement="right" title="Change Password"></i>
                        <span>Change Password</span>
                    </a>

                </div>
            </div>
        </div>

        <div class="sidebar__actions">

            <a id="theme-button" class="sidebar__link sidebar__theme">
                <i class="bi bi-moon-fill" data-bs-toggle="tooltip" data-bs-placement="right" title="Theme"></i>
                <span>Theme</span>
            </a>
            
            <a href="{% url 'logout' %}" class="sidebar__link">
                <i class='bx bxs-log-out' data-bs-toggle="tooltip" data-bs-placement="right" title="Logout"></i>
                <span>Logout</span>
            </a>
        </div>
    </div>
</nav>

templates/partials/table.html
<table class="table table-hover">
    <thead>
      <tr>
        <th>S.No</th>
        <th>Task Name</th>
        <th>Description</th>
        <th>Finish Date</th>
        <th>Status Priority</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        {% for task in page_task %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ task.name }}</td>
        <td>{{ task.description }}</td>
        <td>{{ task.finishDate }}</td>
        
        <td>
            {% if task.status == 'Incomplete'%}
                <i class="bi bi-hourglass-split text-secondary" data-bs-toggle="tooltip" title="Pending"></i>
            {% else %}
                <i class="bi bi-check-square-fill text-success" data-bs-toggle="tooltip" title="Completed"></i>
             {% endif %}
             {% if task.priority == 'Unmark' %}
                <i class='bi bi-bookmark-dash-fill text-info' data-bs-toggle="tooltip" title="Unmark"></i>
            {% elif task.priority == 'Flagged' %}
                <i class='bi bi-flag-fill text-warning' data-bs-toggle="tooltip" title="Flagged"></i>
            {% else %}
                <i class='bi bi-star-fill text-warning' data-bs-toggle="tooltip" title="Star"></i>
            {% endif %}
        </td>
            
        <td>
            <!-- Edit Button -->
            <a href="#" class="edit-task" data-task-id="{{ task.id }}" data-bs-toggle="modal" data-bs-target="#editTaskModal">
                <i class="bi bi-pencil-square text-secondary" data-bs-toggle="tooltip" title="Edit"></i>
            </a>
        
            <!-- Delete Button -->
            <a href="#" class="delete-task" data-task-id="{{ task.id }}" data-bs-toggle="modal" data-bs-target="#deleteTaskModal">
                <i class="bi bi-trash3-fill text-danger" data-bs-toggle="tooltip" title="Delete"></i>
            </a>            
        </td>
      </tr>
        {% endfor %}
    </tbody>          
</table>

templates/partials/taskPopupModal.html
<!-- Create Task Button COde -->
<div class="addTask" data-bs-toggle="tooltip" data-bs-placement="top" title="Add Task">
    <a href="#" data-bs-toggle="modal" data-bs-target="#addTaskModal">
        <i class='bx bx-plus'></i>
    </a>
</div>


<!-- POP UP MODEL FOR TASK -->
<div class="modal fade" id="addTaskModal" tabindex="-1" aria-labelledby="addTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addTaskModalLabel">Add New Task</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Task Form -->
                <form id="addTaskForm" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="text" class="form-control" id="name" placeholder="Enter Task Name" name="name" required>
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" id="description" name="description" rows="3"
                            placeholder="Enter Task description"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="finishDate" class="form-label">Task Date:</label>
                        <input type="date" id="finishDate" name="finishDate" class="form-control datepicker" placeholder="YYYY-MM-DD" required>
                    </div>
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <label for="start_time" class="form-label">Task Start Time:</label>
                            <input type="time" id="start_time" name="start_time" class="form-control timepicker" placeholder="HH:MM" required>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <label for="end_time" class="form-label">Task Finish Time:</label>
                            <input type="time" id="end_time" name="end_time" class="form-control timepicker" placeholder="HH:MM" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Create Task</button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Edit Task Modal -->
<div class="modal fade" id="editTaskModal" tabindex="-1" aria-labelledby="editTaskLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editTaskLabel">Edit Task</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="editTaskForm" method="POST">
                    {% csrf_token %}
                    <input type="hidden" id="task_id" name="id">

                    <div class="mb-3">
                        <label for="task_name" class="form-label">Task Name</label>
                        <input type="text" class="form-control" id="task_name" name="task_name" required>
                    </div>

                    <div class="mb-3">
                        <label for="task_description" class="form-label">Description</label>
                        <textarea id="task_description" name="task_description" rows="3" class="form-control"></textarea>
                    </div>
                    <div class="row mb-3">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <label for="task_status" class="form-label">Status</label>
                            <select class="form-control" id="task_status" name="task_status">
                                <option value="Incomplete">Incomplete</option>
                                <option value="Complete">Complete</option>
                            </select>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <label for="task_priority" class="form-label">Priority</label>
                            <select class="form-control" id="task_priority" name="task_priority">
                                <option value="Unmark">Unmark</option>
                                <option value="Flagged">Flagged</option>
                                <option value="Star">Star</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="finish_Date" class="form-label">Task Date:</label>
                        <input type="date" id="finish_Date" name="finish_Date" class="form-control datepicker" required>
                    </div>
                    <div class="row mb-3">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <label for="start-time" class="form-label">Task Start Time:</label>
                            <input type="text" id="start-time" name="start-time" class="form-control timepicker" required>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <label for="end-time" class="form-label">Task Finish Time:</label>
                            <input type="text" id="end-time" name="end-time" class="form-control timepicker" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                    
                </form>
                
            </div>
        </div>
    </div>
</div>


<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteTaskModal" tabindex="-1" aria-labelledby="deleteTaskLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteTaskLabel">Confirm Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="deleteTaskForm" method="POST">
                    {% csrf_token %}
                    Are you sure you want to delete this task?
                    <input type="hidden" id="taskid">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>
            </div>
        </div>
    </div>
</div>

templates/partials/tasktab.html
{% if data.taskCreated %}
<div class="row">
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12 mb-3">
        <div class="tab h-100">
            <div class="tabTitle bg-primary bg-gradient">
                <h3>Total Task Created</h3>
            </div>
            <div class="tabBody">
                <h2>{{ data.taskCreated }} Tasks</h2>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12 mb-3">
        <div class="tab h-100">
            <div class="tabTitle bg-warning bg-gradient">
                <h3>Pending Task</h3>
            </div>
            <div class="tabBody">
                <h2>{{ data.Incomplete }} Tasks</h2>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12 mb-3">
        <div class="tab h-100">
            <div class="tabTitle bg-info bg-gradient">
                <h3>Completed Task</h3>
            </div>
            <div class="tabBody">
                <h2>{{ data.completed }} Tasks</h2>
            </div>
        </div>
    </div>
</div>
{% endif %}